unit hope;

interface

	const
		HTLC_HDR_FILE_HASH = $00000EE0;
		HTLC_DATA_HASH_MD5 = $0E80;
		HTLC_DATA_HASH_HAVAL = $0E81;
		HTLC_DATA_HASH_SHA1 = $0E82;
		HTLC_DATA_ICON_CICN = $0E90;
		HTLS_DATA_SID = $0E67;
		DATA_SESSIONKEY = $0E03;
		DATA_MAC_ALG = $0E04;
		HTLS_DATA_CIPHER_ALG = $0EC1;
		HTLC_DATA_CIPHER_ALG = $0EC2;
		HTLS_DATA_CIPHER_MODE = $0EC3;
		HTLC_DATA_CIPHER_MODE = $0EC4;
		HTLS_DATA_CIPHER_IVEC = $0EC5;
		HTLC_DATA_CIPHER_IVEC = $0EC6;
		HTLS_DATA_CHECKSUM_ALG = $0EC7;
		HTLC_DATA_CHECKSUM_ALG = $0EC8;
		HTLS_DATA_COMPRESS_ALG = $0EC9;
		HTLC_DATA_COMPRESS_ALG = $0ECA;

implementation

end.
