unit irc;

interface

	const
		DATA_IRC_OLD_NICK = $0400;

		IRC_RPL_WELCOME = '001';
		IRC_RPL_YOURHOST = '002';
		IRC_RPL_CREATED = '003';
		IRC_RPL_MYINFO = '004';
		IRC_RPL_BOUNCE = '005';
		IRC_RPL_USERHOST = '302';
		IRC_RPL_ISON = '303';
		IRC_RPL_AWAY = '301';
		IRC_RPL_UNAWAY = '305';
		IRC_RPL_NOAWAY = '306';
		IRC_RPL_WHOISUSER = '311';
		IRC_RPL_WHOISSERVER = '312';
		IRC_RPL_WHOISOPERATOR = '313';
		IRC_RPL_WHOISIDLE = '317';
		IRC_RPL_ENDOFWHOIS = '318';
		IRC_RPL_WHOISCHANNELS = '319';
		IRC_RPL_WHOASUSER = '314';
		IRC_RPL_ENDOFWHOAS = '369';
		IRC_RPL_LIST = '322';
		IRC_RPL_LISTEND = '323';
		IRC_RPL_UNIQOPIS = '325';
		IRC_RPL_CHANNELMODEIS = '324';
		IRC_RPL_NOTOPIC = '331';
		IRC_RPL_TOPIC = '332';
		IRC_RPL_INVITING = '341';
		IRC_RPL_SUMMONING = '342';
		IRC_RPL_INVITELIST = '346';
		IRC_RPL_ENDOFINVITELIST = '347';
		IRC_RPL_EXCEPTLIST = '348';
		IRC_RPL_ENDOFEXCEPTLIST = '349';
		IRC_RPL_VERSION = '351';
		IRC_RPL_WHOREPLY = '352';
		IRC_RPL_ENDOFWHO = '315';
		IRC_RPL_NAMREPLY = '353';
		IRC_RPL_ENDOFNAMES = '366';
		IRC_RPL_LINKS = '364';
		IRC_RPL_ENDOFLINKS = '365';
		IRC_RPL_BANLIST = '367';
		IRC_RPL_ENDOFBANLIST = '368';
		IRC_RPL_INFO = '371';
		IRC_RPL_ENDOFINFO = '374';
		IRC_RPL_MOTDSTART = '375';
		IRC_RPL_MOTD = '372';
		IRC_RPL_ENDOFMOTD = '376';
		IRC_RPL_YOUREOPER = '381';
		IRC_RPL_REHASHING = '382';
		IRC_RPL_YOURESERVER = '383';
		IRC_RPL_TIME = '391';
		IRC_RPL_USERSTART = '392';
		IRC_RPL_USERS = '393';
		IRC_RPL_ENDOFUSERS = '394';
		IRC_RPL_NOUSERS = '395';
		IRC_ERR_NOSUCHNICK = '401';
		IRC_ERR_NOSUCHSERVER = '402';
		IRC_ERR_NOSUCHCHANNEL = '403';
		IRC_ERR_CANNOTSENDTOCHAN = '404';
		IRC_ERR_TOOMANYCHANNELS = '405';
		IRC_ERR_WASNOSUCHNICK = '406';
		IRC_ERR_TOOMANYTARGETS = '407';
		IRC_ERR_NOSUCHSERVICE = '408';
		IRC_ERR_NOORIGIN = '409';
		IRC_ERR_NORECIPIENT = '411';
		IRC_ERR_NOTEXTTOSEND = '412';
		IRC_ERR_NOTOPLEVEL = '413';
		IRC_ERR_WILDTOPLEVEL = '414';
		IRC_ERR_BADMASK = '415';
		IRC_ERR_UNKNOWNCOMMAND = '421';
		IRC_ERR_NOMOTD = '422';
		IRC_ERR_NOADMIINFO = '423';
		IRC_ERR_FILEERROR = '424';
		IRC_ERR_NOnICKNAMEGIVEN = '431';
		IRC_ERR_ERRONEUSNICKNAME = '432';
		IRC_ERR_NICKNAMEINUSE = '433';
		IRC_ERR_NICKCOLLISION = '436';
		IRC_ERR_UNAVAILRESOURCE = '437';
		IRC_ERR_USERNOTINCHANNEL = '441';
		IRC_ERR_NOLOGIN = '444';

implementation

end.
